package com.tdil.d2d.persistence;

public interface ActivityAction {

	String REGISTER = "REGISTER";
	String LOGIN = "LOGIN";
	String POST_OFFER = "POST_OFFER";
	String APPLY_TO_OFFER = "APPLY_TO_OFFER";
	String ACCEPT_OFFER = "ACCEPT_OFFER";
	String REJECT_OFFER = "REJECT_OFFER";
	String ADD_GEO_LEVEL = "ADD_GEO_LEVEL";
	String ADD_SPECIALTY = "ADD_SPECIALTY";
	String SET_LICENSE = "SET_LICENSE";
	String CHANGE_INSTITUTION_TYPE = "CHANGE_INSTITUTION_TYPE";
	String ADD_TASK_TO_PROFILE = "ADD_TASK_TO_PROFILE";
	String REMOVE_TASK_FROM_PROFILE = "REMOVE_TASK_FROM_PROFILE";;
}
