package com.tdil.d2d.utils;

public class Constants {
	
	public final static String SYSTEM_PROPERTY_PROMO_SUSCRIPTION_ENABLED = "PROMO_SUSCRIPTION_ENABLED";
	
	public final static String SYSTEM_PROPERTY_PROMO_SUSCRIPTION_DAYS = "PROMO_SUSCRIPTION_DAYS";
	
	public final static String SYSTEM_PROPERTY_IOS_LAST_IMPORTANT_VERSION = "IOS_LAST_IMPORTANT_VERSION";
	
	public final static String SYSTEM_PROPERTY_ANDROID_LAST_IMPORTANT_VERSION = "ANDROID_LAST_IMPORTANT_VERSION";

}
