version: '2'
services:
  web:
    image: "tomcat:7.0.73-jre8-alpine"
    ports:
      - "8080:8080"
      - "8443:8443"

    environment:
      JAVA_OPTS: -Dlog4j.configurationFile=conf/app/localhost/log4j2.xml -Dspring.profiles.active=docker -Duser.timezone=GMT-0

    volumes:
          - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
    depends_on:
      - db
  db:
    image: "mysql"
    volumes:
      - ../sql/localidades.sql:/docker-entrypoint-initdb.d/localidades.sql:ro
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: d2d
       MYSQL_USER: root
       MYSQL_PASSWORD: root
  test:
      image: "mysql"
      volumes:
        - ../sql/localidades.sql:/docker-entrypoint-initdb.d/localidades.sql:ro
      ports:
        - "3306:3306"
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: d2d
         MYSQL_USER: root
         MYSQL_PASSWORD: root
